name: Run Card Scraper

# Triggers the workflow on push to the main branch and on a schedule
on:
  push:
    branches:
      - main  # Change to your default branch name if different
  schedule:
    - cron: "0 * * * *"  # Runs every hour (adjust this cron expression to your preference)

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run card scraper
        run: node cardScraper.js
        env:
          BOT_EMAIL: ${{ secrets.BOT_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SEND_EMAIL: ${{ secrets.SEND_EMAIL }}
