name: Run Card Scraper

on:
  push:
    branches:
      - main  
  schedule:
    - cron: "0 */8 * * *"  # Runs every 8 hours

jobs:
  scrape:
    runs-on: ubuntu-latest
    #timeout-minutes: 355  # Set the maximum runtime to 6 hours (360 minutes)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run card scraper
        run: node cardScraper.js
        env:
          BOT_EMAIL: ${{ secrets.BOT_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SEND_EMAIL: ${{ secrets.SEND_EMAIL }}
